### ISSUE TITLE
Creating to zip?

### ISSUE THREAD

**Issue by DaneViking** [elpatron68/cpupdate#1]
Hi Elpatron68!

Great add-on. Makes the update process a lot easier! 👍 

However, I was wondering if you will be able to create the mod folder as a zip file in the future?

Regards,
DaneViking

**Comment by elpatron68** [comment]
@DaneViking Thanks. That´s somehow complicated because I would have to extract the file to parse the currently installed version. I see no big disadvantage in using the directory.

**Comment by elpatron68** [comment]
I think I will implement ZIP-deployment in the next version.

**Comment by elpatron68** [comment]
done.
