### ISSUE TITLE
update for Farming Simulator 22

### ISSUE THREAD

**Issue by garo73** [elpatron68/cpupdate#12]
Hi Sir, is it possible to have a "cpupdater" update for Farming Simulator 22? In any case, thank you!

**Comment by Poppei** [comment]
[cpupdate_portable.zip](https://github.com/elpatron68/cpupdate/files/7834927/cpupdate_portable.zip)
Try this, unpack and paste

**Comment by elpatron68** [comment]
I didn´t buy the game, yet, so no, not at the moment.
