### ISSUE TITLE
CPupdate für LS22

### ISSUE THREAD

**Issue by derJan2001** [elpatron68/cpupdate#13]
Moin nach Kiel.
kannst Du Dein Script auch für LS22 anpassen? 
Ich habe es für LS19 bis zum letzten Tag genutzt ;-)

Gruß aus SH

**Comment by elpatron68** [comment]
Hallo Jan, leider nein, das Spiel hat für mich seinen Reiz verloren, hab's nicht gekauft und kann das Script daher nicht anpassen und testen.GrüßeAm 24.01.2022 07:55 schrieb derJan2001 ***@***.***>:

Moin nach Kiel.

kannst Du Dein Script auch für LS22 anpassen?

Ich habe es für LS19 bis zum letzten Tag genutzt ;-)

Gruß aus SH

**Comment by elpatron68** [comment]
Ich habe ein Powershell Script für FS22-Courseplay und Autodrive Updates geschrieben. Siehe [hier](https://gist.github.com/elpatron68/45780b2ebee88f887d7f3464004d4dc3).
