### ISSUE TITLE
Not updating

### ISSUE THREAD

**Issue by Supermillhouse** [elpatron68/cpupdate#2]
The update is failing for me, possibly because I have a "space" in my username and the directory locations are failing. By the looks of it the backup is the issue.

![untitled](https://cloud.githubusercontent.com/assets/5963597/20950446/ae1dcac6-bc17-11e6-95bb-307ee856f6ec.png)

**Comment by Supermillhouse** [comment]
There are a few %backupdir% with no quotation marks around them, I have added them in and it works OK now. :)

**Comment by elpatron68** [comment]
Hi @Supermillhouse,
thanks a lot, I didn´t test that case. I will fix it in the next version - perhaps today.

**Comment by elpatron68** [comment]
fixed
