### ISSUE TITLE
Small Typo

### ISSUE THREAD

**Issue by gec100** [elpatron68/cpupdate#3]
you have declared autoclose with "NO", when you are checking for "No". So program always closes at the end.

Otherwise, nice little program :) 👍

**Comment by elpatron68** [comment]
thanks, fixed with 1.3

**Comment by Supermillhouse** [comment]
The "if"  on line 238 is still looking for a lower case "o"
The "set" on line 40 is upper case "O"
I am pretty sure this is still the case in 1.3
I only checked the source code on the release though.
