### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by SteelAnxiety** [elpatron68/cpupdate#8]
I must be missing something because it was working for 2017, freshly downloaded the new version and I get this.

![capture](https://user-images.githubusercontent.com/23746972/52128014-d745a800-2601-11e9-9dfe-d03d83c13b86.PNG)

I'm sure I am just missing something, but can you tell me what it might be?

Thanks for a great script, its life-changing during this beta phase.

**Comment by shadow250** [comment]
lose the quotes around 2019  maybe?
i posted instruction to fix it below or copy this file: https://www.dropbox.com/s/j6cthbczzyp1u0e/cpupdate_portable.zip?dl=0  to your csdownloader folder or you may need to get the mod install file from here  https://github.com/elpatron68/cpupdate  or here.  https://github.com/elpatron68/cpupdate/releases
