### ISSUE TITLE
stuck on load scree for courseplay fs19

### ISSUE THREAD

**Issue by dmatthunt** [elpatron68/cpupdate#9]
I have a log file but still stuck on load screen

**Comment by dmatthunt** [comment]
[log.txt](https://github.com/elpatron68/cpupdate/files/3639974/log.txt)

**Comment by Terp88** [comment]
I was looking for something with a similar issue. Courseplay used to work great for me in FS19, then one day I went to play and was stuck on the loading screen. When I remove courseplay from my mods folder, it lets me into the game.ninhavenupdated my game and used several software versions of courseplay and it hasn’t fixed it. Would love to figure out how to fix it and get it back.

**Comment by elpatron68** [comment]
You should ask at the official Couresplay project site as this is just a packageing tool. I would recommend to disable all other mods and start in an empty savegame slot to see what causes the problem.
